name: Continuous Integration - Stratify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file stratify/pom.xml

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        (
          startsWith(github.base_ref, 'main') ||
          startsWith(github.base_ref, 'sprint-')
        )
      )

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file stratify/pom.xml
