name: Continuous Integration - Stratify Backend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: appdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout frontend (Vue)
        uses: actions/checkout@v3

      - name: Checkout backend (Spring Boot)
        uses: actions/checkout@v3
        with:
          repository: usuario/repo-backend
          path: backend

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file stratify/pom.xml

  test:
    name: Testes unitários
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        (
          startsWith(github.base_ref, 'main') ||
          startsWith(github.base_ref, 'sprint-')
        )
      )

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file stratify/pom.xml
  
