name: Continuous Integration - Stratify

on:
  push:
    branches: [ "main", "sprint-1", "sprint-2" ]
  pull_request:
    branches: [ "main", "sprint-1", "sprint-2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file stratify/pom.xml
