-- liquibase formatted sql

-- changeset santo:1748049584373-1
CREATE TABLE "fato_eficiencia_user_story" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 115) NOT NULL, "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_user_story" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tempo_medio" FLOAT8, "id_projeto" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT "fato_eficiencia_user_story_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-2
CREATE TABLE "fato_progresso_user_stories" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_tag" BIGINT, "id_projeto" BIGINT, "id_status" BIGINT, "quantidade_user_stories" BIGINT, CONSTRAINT "fato_progresso_user_stories_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-3
CREATE TABLE "dim_tag" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 21) NOT NULL, "nome" VARCHAR(255) NOT NULL, CONSTRAINT "dim_tag_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-4
CREATE TABLE "dim_projeto" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 29) NOT NULL, "nome" VARCHAR(255) NOT NULL, CONSTRAINT "dim_projeto_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-5
CREATE TABLE "dim_status" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 8) NOT NULL, "tipo" VARCHAR(255) NOT NULL, CONSTRAINT "dim_status_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-6
CREATE TABLE "fato_status_user_story" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 28) NOT NULL, "id_status" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_projeto" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quantidade_user_story" INTEGER, CONSTRAINT "fato_status_user_story_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-7
CREATE TABLE "fato_tag_user_story" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 39) NOT NULL, "id_tag" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_projeto" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quantidade_user_story" INTEGER, CONSTRAINT "fato_tag_user_story_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-8
CREATE TABLE "dim_user_story" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 105) NOT NULL, "assunto" VARCHAR(255), "criado_em" TIMESTAMP WITH TIME ZONE, "finalizado_em" TIMESTAMP WITH TIME ZONE, "bloqueado" BOOLEAN, "encerrado" BOOLEAN, "data_limite" TIMESTAMP WITH TIME ZONE, "id_status" BIGINT NOT NULL, "id_taiga" BIGINT NOT NULL, "id_usuario" BIGINT NOT NULL, "id_projeto" BIGINT NOT NULL, "id_sprint" BIGINT, CONSTRAINT "dim_user_story_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-9
CREATE TABLE "dim_usuario" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 54) NOT NULL, "nome" VARCHAR(100), "email" VARCHAR(100), "senha" VARCHAR(255), "role" VARCHAR(20) DEFAULT 'OPERADOR' NOT NULL, "is_enable" BOOLEAN DEFAULT FALSE NOT NULL, "id_gestor" BIGINT, "require_reset" BOOLEAN DEFAULT FALSE, CONSTRAINT "dim_usuario_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-10
CREATE TABLE "dim_periodo" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 20) NOT NULL, "nome" VARCHAR(100), CONSTRAINT "dim_periodo_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-11
CREATE TABLE "fato_user_story_temporais" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 37) NOT NULL, "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_periodo" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_projeto" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quantidade_user_stories_finalizadas" INTEGER, "quantidade_user_stories_criadas" INTEGER, CONSTRAINT "fato_user_story_temporais_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-12
CREATE TABLE "dim_sprint" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL, "nome" VARCHAR(20) NOT NULL, CONSTRAINT "dim_sprint_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-13
CREATE TABLE "dim_status_historico" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL, "id_user_story" BIGINT NOT NULL, "data_retrabalho" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "id_status" BIGINT NOT NULL, CONSTRAINT "dim_status_historico_pkey" PRIMARY KEY ("id"));

-- changeset santo:1748049584373-14
ALTER TABLE "dim_usuario" ADD CONSTRAINT "dim_usuario_unique" UNIQUE ("email");

-- changeset santo:1748049584373-15
CREATE TABLE "relacionamento_projeto_usuario" ("id_usuario" BIGINT NOT NULL, "id_projeto" BIGINT NOT NULL, CONSTRAINT "pk_relacionamento_pu" PRIMARY KEY ("id_usuario", "id_projeto"));

-- changeset santo:1748049584373-16
CREATE TABLE "relacionamento_tag_user_story" ("id_tag" BIGINT NOT NULL, "id_user_story" BIGINT NOT NULL, CONSTRAINT "pk_relacionamento_tag_user_story" PRIMARY KEY ("id_tag", "id_user_story"));

-- changeset santo:1748049584373-17
ALTER TABLE "dim_user_story" ADD CONSTRAINT "fk_dus_projeto" FOREIGN KEY ("id_projeto") REFERENCES "dim_projeto" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-18
ALTER TABLE "dim_user_story" ADD CONSTRAINT "fk_dus_status" FOREIGN KEY ("id_status") REFERENCES "dim_status" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-19
ALTER TABLE "dim_user_story" ADD CONSTRAINT "fk_dus_usuario" FOREIGN KEY ("id_usuario") REFERENCES "dim_usuario" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-20
ALTER TABLE "fato_status_user_story" ADD CONSTRAINT "fk_ft_projeto_us" FOREIGN KEY ("id_projeto") REFERENCES "dim_projeto" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-21
ALTER TABLE "fato_tag_user_story" ADD CONSTRAINT "fk_ft_projeto_us" FOREIGN KEY ("id_projeto") REFERENCES "dim_projeto" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-22
ALTER TABLE "fato_user_story_temporais" ADD CONSTRAINT "fk_ft_projeto_us_temporais" FOREIGN KEY ("id_projeto") REFERENCES "dim_projeto" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-23
ALTER TABLE "fato_status_user_story" ADD CONSTRAINT "fk_ft_st_us" FOREIGN KEY ("id_status") REFERENCES "dim_status" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-24
ALTER TABLE "fato_tag_user_story" ADD CONSTRAINT "fk_ft_tag_us" FOREIGN KEY ("id_tag") REFERENCES "dim_tag" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-25
ALTER TABLE "fato_user_story_temporais" ADD CONSTRAINT "fk_ft_us_periodo_temporais" FOREIGN KEY ("id_periodo") REFERENCES "dim_periodo" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-26
ALTER TABLE "fato_eficiencia_user_story" ADD CONSTRAINT "fk_ft_user_story_us_eficiencia" FOREIGN KEY ("id_user_story") REFERENCES "dim_user_story" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-27
ALTER TABLE "fato_eficiencia_user_story" ADD CONSTRAINT "fk_ft_usuario_us_eficiencia" FOREIGN KEY ("id_usuario") REFERENCES "dim_usuario" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-28
ALTER TABLE "dim_usuario" ADD CONSTRAINT "fk_id_gestor_usuario" FOREIGN KEY ("id_gestor") REFERENCES "dim_usuario" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset santo:1748049584373-29
ALTER TABLE "fato_eficiencia_user_story" ADD CONSTRAINT "fk_projeto" FOREIGN KEY ("id_projeto") REFERENCES "dim_projeto" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset santo:1748049584373-30
ALTER TABLE "relacionamento_projeto_usuario" ADD CONSTRAINT "fk_relacionamento_pu_projeto" FOREIGN KEY ("id_projeto") REFERENCES "dim_projeto" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-31
ALTER TABLE "relacionamento_projeto_usuario" ADD CONSTRAINT "fk_relacionamento_pu_usuario" FOREIGN KEY ("id_usuario") REFERENCES "dim_usuario" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-32
ALTER TABLE "relacionamento_tag_user_story" ADD CONSTRAINT "fk_relacionamento_tu_tag" FOREIGN KEY ("id_tag") REFERENCES "dim_tag" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-33
ALTER TABLE "relacionamento_tag_user_story" ADD CONSTRAINT "fk_relacionamento_tu_user_story" FOREIGN KEY ("id_user_story") REFERENCES "dim_user_story" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-34
ALTER TABLE "dim_user_story" ADD CONSTRAINT "fk_sprint_us" FOREIGN KEY ("id_sprint") REFERENCES "dim_sprint" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset santo:1748049584373-35
ALTER TABLE "dim_status_historico" ADD CONSTRAINT "fk_staus_historico" FOREIGN KEY ("id_status") REFERENCES "dim_status" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset santo:1748049584373-36
ALTER TABLE "dim_status_historico" ADD CONSTRAINT "fk_user_story_status_historico" FOREIGN KEY ("id_user_story") REFERENCES "dim_user_story" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

